import Head from "next/head";
import Link from "next/link";
import { Header } from "@/components/Header";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>J.A Artsanato</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="container mx-auto pb-12 bg-fixed bg-center bg-cover" >
        <Header />

        <div className="p-4">
          <h1 className='font-bold text-4xl text-pink-500 mt-6 text-center'>Conheça a artista</h1>

          <div className="mt-6 flex justify-center">
            <div className='flex justify-center w-full md:w-1/2 relative rounded-2xl overflow-hidden'>
              <Image
                src='/regina_index.jpg'
                alt="Descrição da imagem"
                layout="responsive"
                width={800}
                height={1200}
                objectFit="cover"
                objectPosition="100% 32%"
              />
            </div>
          </div>

          <div className="mt-6 text-lg text-gray-700  text-justify">
            <p>Regina Monfort é uma artista apaixonada pelo artesanato, transformando sua criatividade em peças únicas e encantadoras. Desde 2009, ela iniciou sua jornada como J.A Artesanato, dedicando-se a criar obras que refletem seu amor e habilidade nesta arte. Ao longo dos anos, Regina tem se destacado pela atenção aos detalhes e pela originalidade de suas criações, conquistando admiradores que apreciam a beleza e a autenticidade do trabalho artesanal.</p>
          </div>

          <div className="mt-6 flex justify-center">
            <Link href='/meus-trabalhos' legacyBehavior>
              <a className="px-4 py-2 bg-pink-500 text-white rounded-lg hover:bg-pink-600">Clique aqui para visualizar meus trabalhos</a>
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
